### ISSUE TITLE
很棒的工作！训练的话占用显存多少呢？

### ISSUE THREAD

**Issue by Mona12138** [QinYang79/RDE#1]
想知道大概占多少显存以及实验在什么类型的GPU运行的

**Comment by QinYang79** [comment]
> 想知道大概占多少显存以及实验在什么类型的GPU运行的

9.5~10.5GB左右，torch版本会带来一点波动。所有实验在3090上运行。谢谢关注！

**Comment by Mona12138** [comment]
谢谢解答！
