### ISSUE TITLE
对label_hat的疑问

### ISSUE THREAD

**Issue by ldq20040602** [QinYang79/RDE#10]
学长您好！看到您的代码把数据分成干净和噪声两类，用label_hat为1和0分别表示，请问是否考虑过label_hat是小数的情形呢？也就是说不完全把数据二分类，而是让偏向干净的数据发挥更大的作用，偏向噪声数据发挥小作用。
非常感谢您百忙之中解答我的疑惑，谢谢您！

**Comment by QinYang79** [comment]
> 学长您好！看到您的代码把数据分成干净和噪声两类，用label_hat为1和0分别表示，请问是否考虑过label_hat是小数的情形呢？也就是说不完全把数据二分类，而是让偏向干净的数据发挥更大的作用，偏向噪声数据发挥小作用。 非常感谢您百忙之中解答我的疑惑，谢谢您！

[issues7](https://github.com/QinYang79/RDE/issues/7)
[issues9](https://github.com/QinYang79/RDE/issues/9)

**Comment by ldq20040602** [comment]
好的学长，谢谢您！
