### ISSUE TITLE
有关于文本增强的问题

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#11]
您代码中对于数据的处理基本与IRRA中的相同，同时您对文本是采用了文本增强的，我想问一下为什么要这样做，因为IRRA中对文本做的增强实际上就是随机的加了一些<|Mask|> token, IRRA中增加这种文本增强是因为其后面要用这些<|Mask|> token做损失，因此IRRA采用这样的方式无可厚非，但RDE中似乎并不需要<|Mask|> token来做损失，并且在本人看来似乎随机的加了一些<|Mask|> token后会让文本的语义变得模糊，并不利于传统的学习方式。

**Comment by QinYang79** [comment]
This is borrowed from the field of image-text matching, [here](https://github.com/woodfrog/vse_infty/blob/master/lib/datasets/image_caption.py).
