### ISSUE TITLE
求cuhkpedes数据集

### ISSUE THREAD

**Issue by AbeanYang97** [QinYang79/RDE#13]
可以分享下这个数据集吗？给作者发邮件了没有回

**Comment by QinYang79** [comment]
> 可以分享下这个数据集吗？给作者发邮件了没有回

Sorry, we cannot redistribute the dataset without the author's authorization.

**Comment by womeizhaol** [comment]
> 可以分享下这个数据集吗？给作者发邮件了没有回

请问现在有这个数据集了吗，可以分享一下吗，万分感谢
