### ISSUE TITLE
想请教您一些关于损失函数设计的研究

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#14]
您这篇文章创新的提出了一种新的损失——TAL，获得了很好的性能，但我仍有一些问题想问。
1.TAL旨在推远所有负样本，达到了比TRL和TRL-S好的多的性能，这一点您在论文中说的已经很明白了。但这么做究竟为什么能提升性能或者鲁棒性呢？个人观点是，TRL只推远最难负样本，而最难负样本通常是损失大的样本，而损失大的样本实际上很可能是噪声。所以同时推远所有负样本可以稀释这种情况造成的不良影响，我不知道我这个想法对不对，如果不对，请您一定指正。
2.在code中我看到在选择负样本时，如果计算i2t损失，也就是选一个干净pair中的图像作为anchor，推远不同pid的文本，而推远的这文本中既有来自干净pair的，也有来自噪声pair的，这是为什么呢？因为我是想，如果在筛选过后分成两个dataloader,一个clean,一个nosiy，如果只在clean set上计算损失，效果会不会更好些？请问您有没有做过类似的实验呢？
3.在传统的(非ReID)图文检索任务中，包括传统NC问题中，损失函数常用hard triplet，但似乎少有人在ReID的数据集上使用这个损失，请问您有没有做过相关实验呢？如果可以，能否分享一下您的宝贵经验与实验结果呢？
4.创建噪声数据集时，我大致明白其原理是，随机互换两个pair的caption，具体如何换，来自noise那个文件的索引。所以请问互换两个caption的两个pair是否一定是不同pid的呢？有没有可能是相同pid的呢？

**Comment by QinYang79** [comment]
You can contact me on WeChat (Please see Poster for QR code) for detailed communication.

**Comment by xzxg001** [comment]
I think your question is very insightful and valuable. I was wondering if you have already solved this issue and if you would be able to share the specifics? 

> 您这篇文章创新的提出了一种新的损失——TAL，获得了很好的性能，但我仍有一些问题想问。 1.TAL旨在推远所有负样本，达到了比TRL和TRL-S好的多的性能，这一点您在论文中说的已经很明白了。但这么做究竟为什么能提升性能或者鲁棒性呢？个人观点是，TRL只推远最难负样本，而最难负样本通常是损失大的样本，而损失大的样本实际上很可能是噪声。所以同时推远所有负样本可以稀释这种情况造成的不良影响，我不知道我这个想法对不对，如果不对，请您一定指正。 2.在code中我看到在选择负样本时，如果计算i2t损失，也就是选一个干净pair中的图像作为anchor，推远不同pid的文本，而推远的这文本中既有来自干净pair的，也有来自噪声pair的，这是为什么呢？因为我是想，如果在筛选过后分成两个dataloader,一个clean,一个nosiy，如果只在clean set上计算损失，效果会不会更好些？请问您有没有做过类似的实验呢？ 3.在传统的(非ReID)图文检索任务中，包括传统NC问题中，损失函数常用hard triplet，但似乎少有人在ReID的数据集上使用这个损失，请问您有没有做过相关实验呢？如果可以，能否分享一下您的宝贵经验与实验结果呢？ 4.创建噪声数据集时，我大致明白其原理是，随机互换两个pair的caption，具体如何换，来自noise那个文件的索引。所以请问互换两个caption的两个pair是否一定是不同pid的呢？有没有可能是相同pid的呢？
