### ISSUE TITLE
关于论文中配图的一点问题

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#3]
<img width="243" alt="image" src="https://github.com/QinYang79/RDE/assets/166200961/9d0ad2ff-5fa1-4886-a79d-ada2b9440309">
您好！这张图片应该是您用来展示数据集中原有的噪声的，但令我不太理解的是您为什么把“grey and black”的描述也标红了？图片中的人物确实是穿的灰色或者黑色的大衣啊？是另有深意，还是不小心标错了？

**Comment by QinYang79** [comment]
看起来像是全黑的，所以我标成红的了。🥲😅

**Comment by QinYang79** [comment]
> <img alt="image" width="243" src="https://private-user-images.githubusercontent.com/166200961/346482215-9d0ad2ff-5fa1-4886-a79d-ada2b9440309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjczNTksIm5iZiI6MTcyMDQyNzA1OSwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ2NDgyMjE1LTlkMGFkMmZmLTVmYTEtNDg4Ni1hNzlkLWFkYTJiOTQ0MDMwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwODI0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTM5OGU2NWYwNzE5MGVhOGM3MmVkY2E0NTM2MDE2N2Y2ZDI5NzYzMDliYjBiZDA2OTM3ODdiMzdiMzc4MmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q2VUxQnDpiJ8T4vu3bR2Q-va7mhu5r1jSEltGQWVMDk"> 您好！这张图片应该是您用来展示数据集中原有的噪声的，但令我不太理解的是您为什么把“grey and black”的描述也标红了？图片中的人物确实是穿的灰色或者黑色的大衣啊？是另有深意，还是不小心标错了？

看起来像是全黑的，所以我标成红的了。🥲😅

**Comment by MeiZaL** [comment]
您好，我是一名研0同学。我的基础代码知识还不够巩固，我在进行代码复现的过程中遇到了问题。在执行train.py文件时还没有进行训练程序就结束了
我通过打断点得知代码执行到这一步就结束了logger.info('Total params: %2.fM' % (sum(p.numel() for p in model.parameters()) / 1000000.0))      我在安装完需要的包之后，引入了CUHK-PEDES数据集，代码也不报错，就是跟下边图片一样不训练，希望能够得到您的指点
![11111111](https://github.com/QinYang79/RDE/assets/175038280/42af2b19-25f3-42c5-89d1-67e11c36993e)

**Comment by showmeyourcodehaha** [comment]
> 您好，我是一名研0同学。我的基础代码知识还不够巩固，我在进行代码复现的过程中遇到了问题。在执行train.py文件时还没有进行训练程序就结束了 我通过打断点得知代码执行到这一步就结束了logger.info('Total params: %2.fM' % (sum(p.numel() for p in model.parameters()) / 1000000.0)) 我在安装完需要的包之后，引入了CUHK-PEDES数据集，代码也不报错，就是跟下边图片一样不训练，希望能够得到您的指点 ![11111111](https://private-user-images.githubusercontent.com/175038280/346635071-42af2b19-25f3-42c5-89d1-67e11c36993e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjc5MzAsIm5iZiI6MTcyMDUyNzYzMCwicGF0aCI6Ii8xNzUwMzgyODAvMzQ2NjM1MDcxLTQyYWYyYjE5LTI1ZjMtNDJjNS04OWQxLTY3ZTExYzM2OTkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjIwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzkyMzY0OTFlZTY2NjVjMDg4YTc0MmIwOGQ2ODViODc3ZGM2M2JhY2VkNTUxMzhhODU0YTlmOGU4ZGMzODgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qij2FFESMShmo5LQwWfuifOa0ft53qJZ8zx6PJBHt8E)

肯定不是执行logger.info出错，这句只是写日志。我不清楚你的运行环境是什么，如果是win建议换成linux，会少很多莫名其妙的问题。

**Comment by QinYang79** [comment]
> 您好，我是一名研0同学。我的基础代码知识还不够巩固，我在进行代码复现的过程中遇到了问题。在执行train.py文件时还没有进行训练程序就结束了 我通过打断点得知代码执行到这一步就结束了logger.info('Total params: %2.fM' % (sum(p.numel() for p in model.parameters()) / 1000000.0)) 我在安装完需要的包之后，引入了CUHK-PEDES数据集，代码也不报错，就是跟下边图片一样不训练，希望能够得到您的指点 ![11111111](https://private-user-images.githubusercontent.com/175038280/346635071-42af2b19-25f3-42c5-89d1-67e11c36993e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjUzMzgsIm5iZiI6MTcyMDk2NTAzOCwicGF0aCI6Ii8xNzUwMzgyODAvMzQ2NjM1MDcxLTQyYWYyYjE5LTI1ZjMtNDJjNS04OWQxLTY3ZTExYzM2OTkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxMzUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2YxMmI4YjViNTU4OGYxNTc1MTJhNTZjMjc5NzJjY2MxMWQ3OTY5ZTQxOWVhMDI2NzFmMWJhZDYzZDM1MDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ANGLISl_nGScICN0DVV1I0gqcNQjF5v4RiUEhCHdPbU)

可以按照IRRA的要求配下环境。
这是我的环境依赖：
[requirements.txt](https://github.com/user-attachments/files/16227635/requirements.txt)

**Comment by MeiZaL** [comment]
好的，谢谢，我已经解决。代码正在跑。




> > 您好，我是一名研0同学。我的基础代码知识还不够巩固，我在进行代码复现的过程中遇到了问题。在执行train.py文件时还没有进行训练程序就结束了 我通过打断点得知代码执行到这一步就结束了logger.info('Total params: %2.fM' % (sum(p.numel() for p in model.parameters()) / 1000000.0)) 我在安装完需要的包之后，引入了CUHK-PEDES数据集，代码也不报错，就是跟下边图片一样不训练，希望能够得到您的指点 ![11111111](https://private-user-images.githubusercontent.com/175038280/346635071-42af2b19-25f3-42c5-89d1-67e11c36993e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjUzMzgsIm5iZiI6MTcyMDk2NTAzOCwicGF0aCI6Ii8xNzUwMzgyODAvMzQ2NjM1MDcxLTQyYWYyYjE5LTI1ZjMtNDJjNS04OWQxLTY3ZTExYzM2OTkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxMzUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2YxMmI4YjViNTU4OGYxNTc1MTJhNTZjMjc5NzJjY2MxMWQ3OTY5ZTQxOWVhMDI2NzFmMWJhZDYzZDM1MDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ANGLISl_nGScICN0DVV1I0gqcNQjF5v4RiUEhCHdPbU)
> 
> 可以按照IRRA的要求配下环境。 这是我的环境依赖： [requirements.txt](https://github.com/user-attachments/files/16227635/requirements.txt)
