### ISSUE TITLE
关于使用数据集CUHK-PEDES运行程序时的一点问题

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#4]
<img width="450" alt="image" src="https://github.com/user-attachments/assets/51aa030f-e2df-4a27-ac8d-92868d59dda0">
我发现在使用CUHK-PEDES数据集运行时会报错，错误表示没有数据集中没有reid_raw.json这个文件，可是我下载的这个数据集的目录如下，好像本来就没有这个文件，是我下载的数据集有问题吗？还是要把caption_all.json改为reid_raw.json？
<img width="262" alt="image" src="https://github.com/user-attachments/assets/c54fe29f-b052-4e6f-bd5a-c4dc9e71d9d2">

**Comment by QinYang79** [comment]
> <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/166200961/348546407-51aa030f-e2df-4a27-ac8d-92868d59dda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjQ5OTMsIm5iZiI6MTcyMDk2NDY5MywicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NDA3LTUxYWEwMzBmLWUyZGYtNGEyNy1hYzhkLTkyODY4ZDU5ZGRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxMzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGMwMzBmNDNjZGNlMDllNzA5MWIyM2U3MWE2ZjMyOWRlNzQ2ZDY1MDAyZjJiNzgyZDI4ODA2ZGRiOWJhOTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pp6DvoMqNgFm9MePWunz-b9dXXAwRs3bNGj2sd9Qyp4"> 我发现在使用CUHK-PEDES数据集运行时会报错，错误表示没有数据集中没有reid_raw.json这个文件，可是我下载的这个数据集的目录如下，好像本来就没有这个文件，是我下载的数据集有问题吗？还是要把caption_all.json改为reid_raw.json？ <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/166200961/348546624-c54fe29f-b052-4e6f-bd5a-c4dc9e71d9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjQ5OTMsIm5iZiI6MTcyMDk2NDY5MywicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NjI0LWM1NGZlMjlmLWIwNTItNGU2Zi1iZDVhLWM0ZGM5ZTcxZDlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxMzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmE1YWE3NTRjZjI3MTY4ZDY0MTVkMmY4N2Y0NDg5Y2E5YTM3ZDE2NzA5YTU0NzdmMjRhNGYzN2FiOTQ5NmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lg-_49PWMVvdhOSbkTvGFWjfl7WyL0waArqvpK4XM9c">

应该是数据集有遗漏。
https://drive.google.com/file/d/15QftHpRJCquiEQyDJ2PG0mAU4ZuTExqJ/view

**Comment by hanjx520** [comment]
> <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/166200961/348546407-51aa030f-e2df-4a27-ac8d-92868d59dda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTIwMTQsIm5iZiI6MTcyMjI1MTcxNCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NDA3LTUxYWEwMzBmLWUyZGYtNGEyNy1hYzhkLTkyODY4ZDU5ZGRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzAyZWM4MDRkZGM4Mzg2ZDgxMTA4NzcxMDIzNzc3OGNjZGFiOTcwZmFiODdiNTQwZDk2MzY3NDI2YzNlNGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qd5W5qoIHiUzbU-cvCBUPaTsfs0ditF7pVhJ63dj9QQ"> 我发现在使用CUHK-PEDES数据集运行时会报错，错误表示没有数据集中没有reid_raw.json这个文件，可是我下载的这个数据集的目录如下，好像本来就没有这个文件，是我下载的数据集有问题吗？还是要把caption_all.json改为reid_raw.json？ <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/166200961/348546624-c54fe29f-b052-4e6f-bd5a-c4dc9e71d9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTIwMTQsIm5iZiI6MTcyMjI1MTcxNCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NjI0LWM1NGZlMjlmLWIwNTItNGU2Zi1iZDVhLWM0ZGM5ZTcxZDlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGI4MWNlNDRiYzVhNmQyNjkyNGRjNDE4YTAyODczYTViMTUwYjkxMWExNGI4ZWRhODgxYjk4NDU3ZDRkNDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._4nDrWWL1HdU7W2Nx2lKlaDubBmrTJjLgyPcseBdEo0">

请问现在解决了嘛，我也有这个疑问

**Comment by QinYang79** [comment]
> https://drive.google.com/file/d/15QftHpRJCquiEQyDJ2PG0mAU4ZuTExqJ/view

Please add it to the dataset directory
reid_raw.json: https://drive.google.com/file/d/15QftHpRJCquiEQyDJ2PG0mAU4ZuTExqJ/view

**Comment by QinYang79** [comment]
> > <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/166200961/348546407-51aa030f-e2df-4a27-ac8d-92868d59dda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTIwMTQsIm5iZiI6MTcyMjI1MTcxNCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NDA3LTUxYWEwMzBmLWUyZGYtNGEyNy1hYzhkLTkyODY4ZDU5ZGRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzAyZWM4MDRkZGM4Mzg2ZDgxMTA4NzcxMDIzNzc3OGNjZGFiOTcwZmFiODdiNTQwZDk2MzY3NDI2YzNlNGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qd5W5qoIHiUzbU-cvCBUPaTsfs0ditF7pVhJ63dj9QQ"> 我发现在使用CUHK-PEDES数据集运行时会报错，错误表示没有数据集中没有reid_raw.json这个文件，可是我下载的这个数据集的目录如下，好像本来就没有这个文件，是我下载的数据集有问题吗？还是要把caption_all.json改为reid_raw.json？ <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/166200961/348546624-c54fe29f-b052-4e6f-bd5a-c4dc9e71d9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTIwMTQsIm5iZiI6MTcyMjI1MTcxNCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NjI0LWM1NGZlMjlmLWIwNTItNGU2Zi1iZDVhLWM0ZGM5ZTcxZDlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGI4MWNlNDRiYzVhNmQyNjkyNGRjNDE4YTAyODczYTViMTUwYjkxMWExNGI4ZWRhODgxYjk4NDU3ZDRkNDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._4nDrWWL1HdU7W2Nx2lKlaDubBmrTJjLgyPcseBdEo0">
> 
> 请问现在解决了嘛，我也有这个疑问

Please add it to the dataset directory
reid_raw.json: https://drive.google.com/file/d/15QftHpRJCquiEQyDJ2PG0mAU4ZuTExqJ/view

**Comment by hanjx520** [comment]
> > > <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/166200961/348546407-51aa030f-e2df-4a27-ac8d-92868d59dda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTIwMTQsIm5iZiI6MTcyMjI1MTcxNCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NDA3LTUxYWEwMzBmLWUyZGYtNGEyNy1hYzhkLTkyODY4ZDU5ZGRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzAyZWM4MDRkZGM4Mzg2ZDgxMTA4NzcxMDIzNzc3OGNjZGFiOTcwZmFiODdiNTQwZDk2MzY3NDI2YzNlNGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qd5W5qoIHiUzbU-cvCBUPaTsfs0ditF7pVhJ63dj9QQ"> 我发现在使用CUHK-PEDES数据集运行时会报错，错误表示没有数据集中没有reid_raw.json这个文件，可是我下载的这个数据集的目录如下，好像本来就没有这个文件，是我下载的数据集有问题吗？还是要把caption_all.json改为reid_raw.json？ <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/166200961/348546624-c54fe29f-b052-4e6f-bd5a-c4dc9e71d9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTIwMTQsIm5iZiI6MTcyMjI1MTcxNCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTQ2NjI0LWM1NGZlMjlmLWIwNTItNGU2Zi1iZDVhLWM0ZGM5ZTcxZDlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTE1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGI4MWNlNDRiYzVhNmQyNjkyNGRjNDE4YTAyODczYTViMTUwYjkxMWExNGI4ZWRhODgxYjk4NDU3ZDRkNDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._4nDrWWL1HdU7W2Nx2lKlaDubBmrTJjLgyPcseBdEo0">
> > 
> > 
> > 请问现在解决了嘛，我也有这个疑问
> 
> Please add it to the dataset directory reid_raw.json: https://drive.google.com/file/d/15QftHpRJCquiEQyDJ2PG0mAU4ZuTExqJ/view

Thank you very much!

**Comment by dyt7788** [comment]
在CUHK-PEDES数据集中没有train_query文件夹，这是什么问题呢，是要预处理吗？help！！！
![Snipaste_2024-09-20_13-26-54](https://github.com/user-attachments/assets/516208c0-e083-4427-b237-b0a334705892)
