### ISSUE TITLE
关于在未人为添加噪声的情况下，CCD方法对噪声的判断能力的问题

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#5]
运行环境：数据集RSTPReid，noisy_rate=0.0
<img width="901" alt="屏幕截图 2024-07-14 224949" src="https://github.com/user-attachments/assets/3c2aed48-9b83-4acd-b860-cbeef30acbc7">

加了两句print，主要是想看看在不人为添加噪声的情况下，CCD（Confident Consensus Division）这个方法会认为数据集中有多少的clean pair(noisy_pair)，换句话说就是用CCD方法来测RSTPReid这个数据集的”本底噪声“，结果如下，令我不太理解。

<img width="661" alt="image" src="https://github.com/user-attachments/assets/568580f1-2f6b-43c6-b548-30f54ed4a78b">

这是最后一个epoch时的运行数据显示，CCD方法认为此时数据集中有18901个clean pair，clean rate时51%左右。我个人是觉得这个值好低啊，因为这是没有人为添加噪声的情况，本底噪声我觉得一般会在3%-20%左右，但是此处却认为有49%的噪声，着实令我费解，尤其是此时的R1还蛮高的，我记得这个数据集在没有噪声的情况下sota的R1也就67%左右。

**Comment by QinYang79** [comment]
> 运行环境：数据集RSTPReid，noisy_rate=0.0 <img alt="屏幕截图 2024-07-14 224949" width="901" src="https://private-user-images.githubusercontent.com/166200961/348551275-3c2aed48-9b83-4acd-b860-cbeef30acbc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjIxMTgsIm5iZiI6MTcyMTM2MTgxOCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTUxMjc1LTNjMmFlZDQ4LTliODMtNGFjZC1iODYwLWNiZWVmMzBhY2JjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNDAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmQ1Y2Q1Y2QxMjY5MjgzNGJhYTA0ZWQxZTUyZGJjMWZmYTg0ZmNhMzQ1OGI2ZDEzOGQ2ZTI3YTBjODc5YTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j13fdJ2OxkkiOsXiBc7VsnlQNxOkParR_jElQhEY9gw">
> 
> 加了两句print，主要是想看看在不人为添加噪声的情况下，CCD（Confident Consensus Division）这个方法会认为数据集中有多少的clean pair(noisy_pair)，换句话说就是用CCD方法来测RSTPReid这个数据集的”本底噪声“，结果如下，令我不太理解。
> 
> <img alt="image" width="661" src="https://private-user-images.githubusercontent.com/166200961/348551627-568580f1-2f6b-43c6-b548-30f54ed4a78b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjIxMTgsIm5iZiI6MTcyMTM2MTgxOCwicGF0aCI6Ii8xNjYyMDA5NjEvMzQ4NTUxNjI3LTU2ODU4MGYxLTJmNmItNDNjNi1iNTQ4LTMwZjU0ZWQ0YTc4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNDAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWMyNmY1Yzc3OTY5MWE1NzBmM2Q4N2FmNzM0ZGE3ZDJiN2VmYjU1MTNmZjdiNDM5M2Y4MDRhOTNjMmUxYzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Y7L3vnsmEjj0QzPWSLYexN0s-YW61TQBkXpIjyezeI">
> 这是最后一个epoch时的运行数据显示，CCD方法认为此时数据集中有18901个clean pair，clean rate时51%左右。我个人是觉得这个值好低啊，因为这是没有人为添加噪声的情况，本底噪声我觉得一般会在3%-20%左右，但是此处却认为有49%的噪声，着实令我费解，尤其是此时的R1还蛮高的，我记得这个数据集在没有噪声的情况下sota的R1也就67%左右。

噪声的划分是基于模型，数据集特性等多个因素来决定的，可能和我们人为视角来看有所差异。RDE实际上主要关注噪声场景下的设置。在人工引入噪声的设置下，RDE能够较好过滤噪声。在没有人为添加噪声的情况，确实可能会和直觉有所偏差。这也可能是未来继续深入讨论的一个点。谢谢关注！
