### ISSUE TITLE
代码小问题导致的程序退出

### ISSUE THREAD

**Issue by Mazai-Liu** [QinYang79/RDE#6]
运行`train.py`训练`RSTPReid`时，程序退出，如图。
![image](https://github.com/user-attachments/assets/5d9ecd98-576f-40ac-acd5-d9b16a6c9fb9)
经调试发现是`model/build.py`中的`self.current_task`是`['sdm', 'id', 'mlm']`，而代码中的判断如下：
![image](https://github.com/user-attachments/assets/454a90ab-064b-426a-b5d7-28f50cd1b490)
字符串大小写不匹配的原因导致走了最后的`else`而退出程序。
修改`model/options.py`中的`sdm`为`SDM`即可。

**Comment by QinYang79** [comment]
> 运行`train.py`训练`RSTPReid`时，程序退出，如图。 ![image](https://private-user-images.githubusercontent.com/64641934/348662182-5d9ecd98-576f-40ac-acd5-d9b16a6c9fb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjI1MjgsIm5iZiI6MTcyMTM2MjIyOCwicGF0aCI6Ii82NDY0MTkzNC8zNDg2NjIxODItNWQ5ZWNkOTgtNTc2Zi00MGFjLWFjZDUtZDliMTZhNmM5ZmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA0MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OGMxZTNhZjQzMmNhNjBlNDM4NzlhMDY2MTQwMDkzYTU4MjlhMjM4NWZjODNjYWJiMzUwMDRiNGNiNWMxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_lSmzeQKBHBcch0_MxoM5PKUT2bUGioz8PbSZm-8OE) 经调试发现是`model/build.py`中的`self.current_task`是`['sdm', 'id', 'mlm']`，而代码中的判断如下： ![image](https://private-user-images.githubusercontent.com/64641934/348663130-454a90ab-064b-426a-b5d7-28f50cd1b490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjI1MjgsIm5iZiI6MTcyMTM2MjIyOCwicGF0aCI6Ii82NDY0MTkzNC8zNDg2NjMxMzAtNDU0YTkwYWItMDY0Yi00MjZhLWI1ZDctMjhmNTBjZDFiNDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA0MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYTU5YWQ0OGMwZGU0MWQ3MmJhYzMwY2FmYWYzMTIzNmYyMjNiNTgzY2JkYzNjODlkNWYyZWI1NTY3MjRmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fn0n7JA-F2h0FxHXxEserdeEUnMS-Ash9Udi6ohRjWY) 字符串大小写不匹配的原因导致走了最后的`else`而退出程序。 修改`model/options.py`中的`sdm`为`SDM`即可。

Great reminder, thanks.
