### ISSUE TITLE
关于对于检测出的噪声数据对的学习策略的问题

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#7]
我看到你们是将预测是否为噪声数据对的结果存在一个长度为数据对对数的tensor中，其中1表示是clean的pair，0表示是noisy的。就是想问一下对于这个tensor中的0的部分是直接当作负样本来学吗？还是说将它们都丢弃？
我刚开始有点自以为是了，就简单的觉得是当作负样本来学，后来做测试时，我将这个预测出的tensor中的所有值都改成0，本来是想看看在高噪声下（>0.5），如果全当成负样本来学，效果会怎么样，后来发现训练时不再打印loss的相关数据了，让我有些奇怪，0的部分是不是实际上并不参与学习。

**Comment by QinYang79** [comment]
> 我看到你们是将预测是否为噪声数据对的结果存在一个长度为数据对对数的tensor中，其中1表示是clean的pair，0表示是noisy的。就是想问一下对于这个tensor中的0的部分是直接当作负样本来学吗？还是说将它们都丢弃？ 我刚开始有点自以为是了，就简单的觉得是当作负样本来学，后来做测试时，我将这个预测出的tensor中的所有值都改成0，本来是想看看在高噪声下（>0.5），如果全当成负样本来学，效果会怎么样，后来发现训练时不再打印loss的相关数据了，让我有些奇怪，0的部分是不是实际上并不参与学习。

Yes, all pairs with a predicted label of 0 are discarded. Please refer to the paper instructions. Thanks for your attention to our work.
