### ISSUE TITLE
关于论文的一点问题

### ISSUE THREAD

**Issue by showmeyourcodehaha** [QinYang79/RDE#9]
能否分享一下您在这篇论文中为什么采用硬标签（0，1）来区分噪声，进而学习呢？因为在这篇论文出来之前已经有不少工作使用了软标签，使用软标签作为一个信任度进行学习。当然我必须的承认即使没有使用软标签，这篇论文的效果依旧很好。但是我仍想知道您是否考虑过这个问题呢？是不是做过实验发现效果不好，能不能分享一些您实验出来的经验呢？万分感谢！

**Comment by QinYang79** [comment]
> 能否分享一下您在这篇论文中为什么采用硬标签（0，1）来区分噪声，进而学习呢？因为在这篇论文出来之前已经有不少工作使用了软标签，使用软标签作为一个信任度进行学习。当然我必须的承认即使没有使用软标签，这篇论文的效果依旧很好。但是我仍想知道您是否考虑过这个问题呢？是不是做过实验发现效果不好，能不能分享一些您实验出来的经验呢？万分感谢！

This paper mainly focus on noisy scenes. When we were experimenting, we found that noisy scenes are prone to noise overfitting using soft correspondence labels, so I chose to use hard correspondence labels.  Thanks for your interest in our work.
